import math
def add(x,y):
    return x+y
def sub(x,y):
    return x-y
def multi(x,y):
    return x*y
def divi(x,y):
    return x/y
def power(x,y):
    return x**y
def sqrt(x):
    return x**0.5
def sin(x):
    return math.sin(x)
def cos(x):
    return math.cos(x)
def tan(x):
    return math.tan(x)