# # # int()
# # # str()
# # # list()
# # # dict()
# # # set()
# # # tuple()
# # # framework
# # l1=[10,20,30,40]
# # print(tuple(l1))
# # print(type(l1))
# # print(set(l1))
# # x=int (input("enter your age:"))
# # print(type(x))
# name=input("Enter your name")
# int(name)
# print (type(name))
age=int(input("Enter your Age: "))
print(age)
print(type(age))  